name = "Flowstar"
uuid = "a8054ddd-9dca-4d20-8ffe-ae96ec1541f1"
authors = ["Adam R. Gerlach and Contributors"]
version = "0.1.0"

[deps]
Flowstar_jll = "857d554b-2109-5851-8b71-fc429cd15c15"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
TaylorModels = "314ce334-5f6e-57ae-acf6-00b6e903104a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
