name = "Flowstar"
uuid = "a8054ddd-9dca-4d20-8ffe-ae96ec1541f1"
authors = ["Adam R. Gerlach and Contributors"]
version = "0.2.4"

[deps]
Flowstar_jll = "857d554b-2109-5851-8b71-fc429cd15c15"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
TaylorModels = "314ce334-5f6e-57ae-acf6-00b6e903104a"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[compat]
Flowstar_jll = "2"
TaylorModels = "0.6"
TypedPolynomials = "0.3"
julia = "1.6"
